version: '3.8'
services:
  db:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo-app
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .  
    container_name: todo-docker
    depends_on:
      - db
    ports:
      - "8080:3000"
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@db:5432/todo-app

volumes:
  postgres_data: